[package]
name = "wasm"
version = "0.1.0"
authors = ["Wesley Oliveira <oliveirawesleyrjg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
yew = "0.19.3"
yew-router = "0.16.0"
